spring:
  cloud:
    gateway:
      routes:
      - id: agenda
        uri: http://demo-conference-agenda/
        predicates:
        - Path=/agenda/*
      - id: c4p
        uri: http://demo-conference-c4p/
        predicates:
        - Path=/c4p/*

